language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - CI=false yarn build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
